#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM PROGRAM0
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,RUN_BUTTON)
  __DECLARE_LOCATED(BOOL,STOP_BUTTON)
  __DECLARE_LOCATED(BOOL,HEAT)
  __DECLARE_LOCATED(BOOL,COOLING)
  __DECLARE_VAR(BOOL,STOP_STATUS)
  __DECLARE_LOCATED(BOOL,SYSTEM_OUT)
  __DECLARE_LOCATED(BOOL,HEAT_OUT)
  __DECLARE_LOCATED(BOOL,COOLING_OUT)
  __DECLARE_VAR(BOOL,RUN_STATUS)
  __DECLARE_LOCATED(INT,ET_IN)
  __DECLARE_LOCATED(INT,BT_IN)
  __DECLARE_LOCATED(INT,AT_IN)
  __DECLARE_LOCATED(INT,CH4_IN)
  TON TON0;

} PROGRAM0;

void PROGRAM0_init__(PROGRAM0 *data__, BOOL retain);
// Code part
void PROGRAM0_body__(PROGRAM0 *data__);
#endif //__POUS_H
